### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by njhunsak** [pnlbwh/TBSS#40]
I pulled the latest version of the TBSS code this morning and tried running tbss_all and got this error:

```
Creating study specific template ...
Traceback (most recent call last):
  File "/fslhome/intj5/apps/pnlbwh/tbss/lib/tbss_all", line 524, in <module>
    main()
  File "/fslhome/intj5/apps/pnlbwh/tbss/lib/tbss_all", line 516, in main
    args= process(args)
  File "/zhome/intj5/apps/pnlbwh/tbss/lib/tbss_single.py", line 186, in process
    warp2tmp= glob(pjoin(args.xfrmDir, f'{c}_FA*1Warp.nii.gz'))[0]
IndexError: list index out of range
```

Here's the full output:

```
tbss_all \
> -i /fslhome/intj5/compute/data/BRAINSCOPE/tbss-studyTemplate/input.csv \
> -c /fslhome/intj5/compute/data/BRAINSCOPE/tbss-studyTemplate/caselist.txt \
> --studyTemplate \
> --modality FA \
> --verbose \
> --noFillHole \
> -n 1 \
> --qc \
> -o /fslhome/intj5/compute/data/BRAINSCOPE/tbss-studyTemplate/


# ===============================================================================
# tbss (2019) pipeline is written by-
# 
# TASHRIF BILLAH
# Brigham and Women's Hospital/Harvard Medical School
# tbillah@bwh.harvard.edu
# 
# ===============================================================================
# See details at https://github.com/pnlbwh/tbss
# Submit issues at https://github.com/pnlbwh/tbss/issues
# View LICENSE at https://github.com/pnlbwh/tbss/blob/master/LICENSE
# ===============================================================================
# __version__ 0.1.5


antsApplyTransforms found
antsRegistrationSyNQuick.sh found
antsMultivariateTemplateConstruction2.sh found
antsRegistration found
dtifit found
tbss_1_preproc found
tbss_skeleton found
distancemap found
All executables are found, program will begin now ...
--study template specified, overriding any provided templates
/fslhome/intj5/apps/pnlbwh/tbss/lib/tbss_all:472: UserWarning: Assuming cases in --caselist correspond to images in --input, make sure they are ordered correctly
  warn('Assuming cases in --caselist correspond to images in --input, make sure they are ordered correctly')


TBSS for modality  FA
/zhome/intj5/apps/pnlbwh/tbss/lib/tbssUtil.py:58: UserWarning: /fslhome/intj5/compute/data/BRAINSCOPE/tbss-studyTemplate/FA/warped exists and will be overwritten
  warn(f'{dir} exists and will be overwritten')
/zhome/intj5/apps/pnlbwh/tbss/lib/tbssUtil.py:58: UserWarning: /fslhome/intj5/compute/data/BRAINSCOPE/tbss-studyTemplate/FA/skeleton exists and will be overwritten
  warn(f'{dir} exists and will be overwritten')
/zhome/intj5/apps/pnlbwh/tbss/lib/tbssUtil.py:58: UserWarning: /fslhome/intj5/compute/data/BRAINSCOPE/tbss-studyTemplate/FA/roi exists and will be overwritten
  warn(f'{dir} exists and will be overwritten')
Preprocessing FA images: eroding them and zeroing the end slices ...
processing sub-141320001_ses-1
processing sub-141320003_ses-1
processing sub-141320003_ses-2
processing sub-141320013_ses-1
processing sub-141320013_ses-2
processing sub-141320014_ses-1
processing sub-141320018_ses-1
processing sub-141320027_ses-1
processing sub-141320027_ses-2
processing sub-141320029_ses-2
processing sub-141320032_ses-1
processing sub-141320032_ses-2
processing sub-141320033_ses-1
processing sub-141320034_ses-1
processing sub-141320035_ses-1
processing sub-141320035_ses-2
processing sub-141320036_ses-1
processing sub-141320036_ses-2
processing sub-141320037_ses-1
processing sub-141320038_ses-1
processing sub-141320039_ses-1
processing sub-141320040_ses-1
processing sub-141320041_ses-1
processing sub-141320043_ses-1
processing sub-141370041_ses-2
processing sub-141370042_ses-1
processing sub-141370042_ses-2
processing sub-141370043_ses-2
processing sub-141370044_ses-1
processing sub-141370044_ses-2
processing sub-141370045_ses-1
processing sub-141370045_ses-2
processing sub-141370046_ses-1
processing sub-141370046_ses-2
processing sub-141370047_ses-1
processing sub-141370047_ses-2
processing sub-141370048_ses-1
processing sub-141370048_ses-2
processing sub-141370049_ses-1
processing sub-141370049_ses-2
processing sub-141370051_ses-1
processing sub-141370051_ses-2
processing sub-141370052_ses-1
processing sub-141370052_ses-2
processing sub-141370053_ses-2
processing sub-141370054_ses-1
processing sub-141370054_ses-2
processing sub-141370055_ses-2
processing sub-141370057_ses-1
processing sub-141370057_ses-2
processing sub-141370058_ses-1
processing sub-141370058_ses-2
processing sub-141370059_ses-1
processing sub-141370059_ses-2
processing sub-141370061_ses-1
processing sub-141370061_ses-2
processing sub-141370062_ses-1
processing sub-141370062_ses-2
processing sub-141370063_ses-2
processing sub-141370064_ses-1
processing sub-141370064_ses-2
processing sub-141370076_ses-1
processing sub-141370077_ses-1
processing sub-141370078_ses-1
processing sub-141370079_ses-1
processing sub-141370080_ses-1
processing sub-141370081_ses-1
processing sub-141370082_ses-1
processing sub-141370083_ses-1
processing sub-141370084_ses-1
processing sub-141370085_ses-1
processing sub-141370086_ses-1
processing sub-141370087_ses-1
processing sub-141370088_ses-1
processing sub-141370089_ses-1
processing sub-141370090_ses-1
processing sub-141370091_ses-1
processing sub-141370093_ses-1
processing sub-141370094_ses-1
processing sub-141370095_ses-1
processing sub-141370098_ses-1
processing sub-141370099_ses-1
processing sub-141400042_ses-1
processing sub-141400042_ses-2
processing sub-141400048_ses-1
processing sub-141400048_ses-2
processing sub-141400049_ses-1
processing sub-141400052_ses-1
processing sub-141400052_ses-2
processing sub-141400053_ses-1
processing sub-141400060_ses-1
processing sub-141400060_ses-2
processing sub-141400062_ses-1
processing sub-141400063_ses-1
processing sub-141400063_ses-2
processing sub-141400065_ses-1
processing sub-141400067_ses-1
processing sub-141400067_ses-2
processing sub-141400068_ses-1
processing sub-141400069_ses-1
processing sub-141400069_ses-2
processing sub-141400070_ses-1
processing sub-141400071_ses-1
processing sub-141400071_ses-2
processing sub-141400073_ses-1
processing sub-141400073_ses-2
processing sub-141400074_ses-1
processing sub-141400075_ses-1
processing sub-141400075_ses-2
processing sub-141400076_ses-1
processing sub-141400077_ses-1
processing sub-141400078_ses-1
processing sub-141400079_ses-1
processing sub-141400079_ses-2
processing sub-141400080_ses-1
processing sub-141400081_ses-1
processing sub-141400081_ses-2
processing sub-141400082_ses-1
processing sub-141410005_ses-1
processing sub-141410015_ses-1
processing sub-141410020_ses-1
processing sub-141410025_ses-1
processing sub-141410026_ses-1
processing sub-141410026_ses-2
processing sub-141410027_ses-1
processing sub-141410027_ses-2
processing sub-141410029_ses-1
processing sub-141410030_ses-1
processing sub-141410031_ses-1
processing sub-141410032_ses-1
processing sub-141410033_ses-1
processing sub-141410033_ses-2
processing sub-141410034_ses-1
processing sub-141410038_ses-1
processing sub-141410038_ses-2
processing sub-141410040_ses-1
processing sub-141410040_ses-2
processing sub-141410042_ses-1
processing sub-141410043_ses-1
Now running "slicesdir" to generate report of all input images
Finished. To view, point your web browser at
file:/lustre/scratch/usr/intj5/data/BRAINSCOPE/tbss-studyTemplate/FA/FA/slicesdir/index.html
Index file location has changed, see  /fslhome/intj5/compute/data/BRAINSCOPE/tbss-studyTemplate/FA/preproc/slicesdir/index.html
Creating study specific template ...
Traceback (most recent call last):
  File "/fslhome/intj5/apps/pnlbwh/tbss/lib/tbss_all", line 524, in <module>
    main()
  File "/fslhome/intj5/apps/pnlbwh/tbss/lib/tbss_all", line 516, in main
    args= process(args)
  File "/zhome/intj5/apps/pnlbwh/tbss/lib/tbss_single.py", line 186, in process
    warp2tmp= glob(pjoin(args.xfrmDir, f'{c}_FA*1Warp.nii.gz'))[0]
IndexError: list index out of range
```

**Comment by tashrifbillah** [comment]
Template creation failed. Given you chose `--verbose`, you should be seeing many log from `antsMultivariateTemplateConstruction2.sh` after the log `Creating study specific template ...`. 
You can do a few things to debug this issue:

1. Remove `/fslhome/intj5/compute/data/BRAINSCOPE/tbss-studyTemplate/template/` directory and try again.

2. Look inside `/fslhome/intj5/compute/data/BRAINSCOPE/tbss-studyTemplate/template` directory and see if you can give us a better picture.

3. Another thing to consider is [Troubleshooting (ii)](https://github.com/pnlbwh/TBSS/blob/master/docs/TUTORIAL.md#troubleshooting)

**Comment by njhunsak** [comment]
By removing the `--verbose` option, that was all I needed to do to fix my issue.

**Comment by tashrifbillah** [comment]
I can't rationalize that, but I am glad you found a solution.
