### ISSUE TITLE
When using multithreading - "ValueError: I/O operation on closed file."

### ISSUE THREAD

**Issue by felenae** [pnlbwh/TBSS#51]
Dear developer team,

I am experiencing an issue when running your TBSS pipeline on ~500 subjects on our HPC. The pipeline starts ok, i.e. "Filling holes inside the brain ...", "Now running slicesdir ...", "Preprocessing FA images: eroding ..." finishes correctly. However, during ANTs registration of FA images to template space the pipeline crashes. The error shown below causes the pipeline to stall, but not to exit. When looking at the batch job report (see below), it does not seem like memory or CPU capacity is the problem. On the other hand, I have previously experienced the same problem on my local machine, where lowering "ncpus" to </= 4 fixed the problem. Considering the need to make the best use of CPUs/Memory when processing large datasets, I was wondering whether you have an idea how to address this issue?

Thanks a lot!

All the best,
Felix

### Version of pnlbwh/TBSS: 
0.1.5

### Installation:  
Singularity container on Centos 7 HPC (64 GB RAM, 2 CPUs with 8 cores each)

### Command-line: 
```
CMD_TBSS="
        tbss_all \
            --caselist $CASELIST \
            --input $IMAGELIST \
            --modality FA,FAt,AD,ADt,RD,RDt,MD,MDt,FW \
            --enigma \
            --outDir $TBSS_DIR \
            --avg \
            --force \
            --verbose \
            --ncpu 8"

singularity run --cleanenv --userns \
    -B . \
    -B $PROJ_DIR \
    -B $TMP_DIR:/tmp \
    $ENV_DIR/tbss_pnl-0.1.5 $CMD_TBSS
```

### Error output:
```
Exception in thread Thread-6:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/csi/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/tbss/lib/antsTemplate.py", line 57, in antsReg
    print(f'fixedImage: {fixedImg}, movingImage: {movingImg}')
ValueError: I/O operation on closed file.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/csi/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/miniconda-latest/envs/csi/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/miniconda-latest/envs/csi/lib/python3.9/multiprocessing/pool.py", line 592, in _handle_results
    cache[job]._set(i, obj)
  File "/opt/miniconda-latest/envs/csi/lib/python3.9/multiprocessing/pool.py", line 778, in _set
    self._error_callback(self._value)
  File "/tbss/lib/tbssUtil.py", line 68, in RAISE
    raise ERR
ValueError: I/O operation on closed file.
slurmstepd: error: *** JOB 1500425 ON node359 CANCELLED AT 2021-10-05T20:58:57 DUE TO TIME LIMIT ***
```

### Batch job report:

```
═══════════════════════════════════════════════════
Overview of std job 1500425 resources (v34.18)
───────────────────────────────────────────────────

Elapsed runtime: 43210 s (12.0 node-hours)

Maximum virtual memory allocation on a node: 48.6 GiB
          Maximum use of local scratch disk: 33.8 MiB
                 Total reads from /home /sw: 50.7 MiB
                     Total reads from /work: 81.0 GiB
                      Total writes to /work: 17.9 GiB
             Total inter-node communication: 22.1 GiB

Average gross compute, I/O, communication load, maximum memory use:

node    │ cpu   mem  swap   disk  iops  /work   comm
        │       GiB   GiB  MiB/s   1/s  MiB/s  MiB/s
════════╪═══════════════════════════════════════════
node359 │ 1.1  12.3   0.0      0     0      2    0.5
────────┼───────────────────────────────────────────
sum:  1 │ 1.1  12.3   0.0      0     0      2    0.5

Average CPU physical core usage, mean over all nodes:

socket  core │ user   sys  iowait   idle
═════════════╪══════════════════════════
     0     0 │ 0.08  0.01    0.00   1.89
     0     1 │ 0.06  0.01    0.00   1.94
     0     2 │ 0.01  0.00    0.00   1.98
     0     3 │ 0.18  0.02    0.00   1.78
     0     4 │ 0.23  0.03    0.00   1.74
     0     5 │ 0.18  0.00    0.00   1.81
     0     6 │ 0.15  0.02    0.00   1.84
     0     7 │ 0.00  0.00    0.00   1.99
     1     0 │ 0.02  0.00    0.00   1.98
     1     1 │ 0.01  0.00    0.00   1.99
     1     2 │ 0.01  0.00    0.00   1.99
     1     3 │ 0.01  0.00    0.00   1.99
     1     4 │ 0.00  0.00    0.00   2.00
     1     5 │ 0.00  0.00    0.00   2.00
     1     6 │ 0.00  0.00    0.00   2.00
     1     7 │ 0.00  0.00    0.00   2.00
─────────────┼──────────────────────────
sum: 2    16 │ 0.95  0.12    0.02  30.89   

Summary:

    Elapsed time: 100% (12.0 out of 12.0 h timelimit)                
             CPU:   6%  (1.0 out of 16 physical CPU cores)           
    Hyperthreads:   0%  (0.0 out of 16 CPU hyperthreads)             
Max. main memory:  20% (12.3 out of 62.0 GiB min. available per node)
       Max. swap:   0%  (0.0 out of  2.0 GiB min. available per node)
──────────────────
End Of Report

```

**Comment by felenae** [comment]
> > where lowering "ncpus" to </= 4 fixed the problem
> 
> Hi Felix, since you already have a way around, we did not spend time on it yet. But we shall in future.

Hi Tashrif, after a few more test runs lowering ncpus did not seem to fix the problem (despite my initial intuition). On the other hand, when I ran the command for only a few (20) subjects there was no problem, while when trying to process around 400 subjects ANTs registration doesn't even get beyond the first iteration of subjects (i.e., e.g. 4 subjects when selecting --ncpu 4). So maybe the multiprocessing option can't handle too many subjects in the job queue?


> I updated the issue description. User had misplaced (```) before. Now it is easier to read.

Thanks!

> > Singularity container on Centos 6 HPC
> 
> I never knew you could run Singularity on CentOS < 7!

Sorry for the typo. It is indeed CentOS 7. I updated the issue accordingly.

> I am suspecting Singularity to be the culprit here. Here is an idea for you to debug--install TBSS natively w/o the Singularity container at your cluster. It should be simple to install. If you can run the same program natively, then we know.

Thanks for your idea. I will look into it!
